In [2]:
import datetime
import pytz
def export_csv(df,name):
  now = datetime.datetime.now().astimezone(pytz.timezone('Asia/Taipei'))
  formatted_time = now.strftime('%Y-%m-%d %HÊôÇ%MÂàÜ%SÁßí')
  df.to_csv('predict_data/'+ name + '_' + formatted_time + ".csv", index=False,encoding="utf_8_sig")

In [1]:
import pandas as pd
test_data = pd.read_csv(r'raw_data/boy or girl 2024 test no ans_missingValue.csv')
test_data

,id,gender,star_sign,phone_os,height,weight,sleepiness,iq,fb_friends,yt,self_intro
0,1,0,Â§©Ë†çÂ∫ß,Apple,NaN,100.0,1.0,87.000,87.0,87.0,GOod
1,2,0,ÈáëÁâõÂ∫ß,Apple,175.0,80.0,3.0,130.000,2000.0,30.0,Easygoing
2,3,0,ÈõôÂ≠êÂ∫ß,Apple,155.0,45.0,3.0,150.000,400.0,9.0,I LOVE INTEL
3,4,0,ËôïÂ•≥Â∫ß,Apple,173.0,85.0,4.0,100.000,2000.0,15.0,"I'm a hard-work man, just do my best to finish..."
4,5,0,Â∞ÑÊâãÂ∫ß,Android,164.0,57.0,4.0,130.000,505.0,2.0,I'm smart
...,...,...,...,...,...,...,...,...,...,...,...
390,391,0,ËôïÂ•≥Â∫ß,Android,160.0,48.0,3.0,75.000,98.0,2.0,Starting by Starting
391,392,0,NaN,Apple,170.0,NaN,NaN,105.000,510.0,NaN,A little bit smart
392,393,0,ÈáëÁâõÂ∫ß,Apple,160.0,45.0,4.0,100.000,600.0,2000.0,Hi
393,394,0,Â∑®ËüπÂ∫ß,NaN,180.0,NaN,NaN,199.999,NaN,60.0,"I'm not beautiful, but smart üòÄ"
394,395,0,Â∞ÑÊâãÂ∫ß,Apple,175.0,69.0,5.0,135.000,200.0,1400.0,Like the shadow

### catboost

In [3]:
raw_data = pd.read_csv(r'raw_data/boy or girl 2024 train_missingValue.csv')
raw_data

,id,gender,star_sign,phone_os,height,weight,sleepiness,iq,fb_friends,yt,self_intro
0,1,2,ËôïÂ•≥Â∫ß,Apple,154.0,43.0,2.0,180.0,583.0,0,Beautiful
1,2,2,ËôïÂ•≥Â∫ß,NaN,156.0,47.0,2.0,130.0,400.0,3.5,Enjoying being who I'm notsss
2,3,1,Â∞ÑÊâãÂ∫ß,Android,170.0,61.0,3.0,90.0,540.0,5,Practice Makes perfect
3,4,1,Â∞ÑÊâãÂ∫ß,Apple,170.0,62.0,4.0,100.0,173.0,5,Straightforward
4,5,2,Â∞ÑÊâãÂ∫ß,Android,158.0,NaN,3.0,NaN,NaN,1.2,Humorous
...,...,...,...,...,...,...,...,...,...,...,...
418,419,1,ËôïÂ•≥Â∫ß,Android,166.0,66.0,4.0,90.0,1000.0,1,I hope i am a super hero.
419,420,1,Áâ°ÁæäÂ∫ß,Android,176.0,65.0,4.0,87.0,1300.0,2,God damn dope
420,421,1,Â§©Áß§Â∫ß,Apple,174.0,72.0,NaN,NaN,NaN,NaN,Sunny
421,422,2,Â§©Ë†çÂ∫ß,Apple,167.0,50.0,3.0,180.0,483.0,10,Light
422,423,1,ÈõôÈ≠öÂ∫ß,Android,NaN,68.0,3.0,66.0,300.0,NaN,super 666666

In [4]:
import pandas as pd
knn_train = pd.read_csv(r'preprocess_data/KNN_withBMI.csv')
knn_train

,id,gender,star_sign,phone_os,height,weight,sleepiness,iq,fb_friends,yt,bmi
0,1,2,7.0,0,1.540,43.0,2.0,180.0,583.0,0.00,18.131219
1,2,2,7.0,0,1.560,47.0,2.0,130.0,400.0,3.50,19.312952
2,3,1,10.0,1,1.700,61.0,3.0,90.0,540.0,5.00,21.107266
3,4,1,10.0,0,1.700,62.0,4.0,100.0,173.0,5.00,21.453287
4,5,2,10.0,1,1.580,61.4,3.0,110.6,498.6,1.20,24.595417
...,...,...,...,...,...,...,...,...,...,...,...
417,419,1,7.0,1,1.660,66.0,4.0,90.0,1000.0,1.00,23.951227
418,420,1,2.0,1,1.760,65.0,4.0,87.0,1300.0,2.00,20.983988
419,421,1,8.0,0,1.740,72.0,3.6,155.6,260000350.0,2.10,23.781213
420,422,2,9.0,0,1.670,50.0,3.0,180.0,483.0,10.00,17.928215
421,423,1,1.0,1,1.716,68.0,3.0,66.0,300.0,1.26,23.092680

In [5]:
df = pd.merge(knn_train, raw_data[['id', 'self_intro']], on='id', how='left')
df

,id,gender,star_sign,phone_os,height,weight,sleepiness,iq,fb_friends,yt,bmi,self_intro
0,1,2,7.0,0,1.540,43.0,2.0,180.0,583.0,0.00,18.131219,Beautiful
1,2,2,7.0,0,1.560,47.0,2.0,130.0,400.0,3.50,19.312952,Enjoying being who I'm notsss
2,3,1,10.0,1,1.700,61.0,3.0,90.0,540.0,5.00,21.107266,Practice Makes perfect
3,4,1,10.0,0,1.700,62.0,4.0,100.0,173.0,5.00,21.453287,Straightforward
4,5,2,10.0,1,1.580,61.4,3.0,110.6,498.6,1.20,24.595417,Humorous
...,...,...,...,...,...,...,...,...,...,...,...,...
417,419,1,7.0,1,1.660,66.0,4.0,90.0,1000.0,1.00,23.951227,I hope i am a super hero.
418,420,1,2.0,1,1.760,65.0,4.0,87.0,1300.0,2.00,20.983988,God damn dope
419,421,1,8.0,0,1.740,72.0,3.6,155.6,260000350.0,2.10,23.781213,Sunny
420,422,2,9.0,0,1.670,50.0,3.0,180.0,483.0,10.00,17.928215,Light
421,423,1,1.0,1,1.716,68.0,3.0,66.0,300.0,1.26,23.092680,super 666666

In [6]:
import re
import numpy as np
# ÊÉÖÁ∑íÂ≠óÂÖ∏Ê®ôË®òÂáΩÊï∏
emotion_keywords = {
    1: ['boy', 'girlfriend', 'man','handsome','87','loser','dxxk','ggininder','fantastic','loser'],  # Áî∑ÁîüÈóúÈçµË©ûÂàóË°®
    -1: ['girl', 'pretty','beautiful','adorable','>.0','cuuuuuuute']  # Â•≥ÁîüÈóúÈçµË©ûÂàóË°®
}

def emotion_label(text):
    # Ê™¢Êü•Ë≥áÊñôÊòØÂê¶ÁÇ∫ÊúâÊïà
    if isinstance(text, str) or isinstance(text, bytes):
        # ÂàÜË©û
        words = re.findall(r'\b\w+\b', text)
        # Ê™¢Êü•Ê≠£Èù¢ÊÉÖÁ∑í
        if any(word in emotion_keywords[1] for word in words):
            return 1

        # Ê™¢Êü•Ë≤†Èù¢ÊÉÖÁ∑í
        if any(word in emotion_keywords[-1] for word in words):
            return -1
        # ‰∏≠ÊñáÂà§ÂÆöÁÇ∫Ê≠£Èù¢
        if re.search(r'[\u4e00-\u9fff]+', text):
            return 1
    # Â¶ÇÊûú‰∏çÊòØÊúâÊïàÔºåËøîÂõû‰∏≠ÊÄßÊÉÖÁ∑í
    return 0

In [7]:
df['self_intro'] = df['self_intro'].str.lower()
df['emotion'] = np.vectorize(emotion_label)(df['self_intro'])
df

,id,gender,star_sign,phone_os,height,weight,sleepiness,iq,fb_friends,yt,bmi,self_intro,emotion
0,1,2,7.0,0,1.540,43.0,2.0,180.0,583.0,0.00,18.131219,beautiful,-1
1,2,2,7.0,0,1.560,47.0,2.0,130.0,400.0,3.50,19.312952,enjoying being who i'm notsss,0
2,3,1,10.0,1,1.700,61.0,3.0,90.0,540.0,5.00,21.107266,practice makes perfect,0
3,4,1,10.0,0,1.700,62.0,4.0,100.0,173.0,5.00,21.453287,straightforward,0
4,5,2,10.0,1,1.580,61.4,3.0,110.6,498.6,1.20,24.595417,humorous,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
417,419,1,7.0,1,1.660,66.0,4.0,90.0,1000.0,1.00,23.951227,i hope i am a super hero.,0
418,420,1,2.0,1,1.760,65.0,4.0,87.0,1300.0,2.00,20.983988,god damn dope,0
419,421,1,8.0,0,1.740,72.0,3.6,155.6,260000350.0,2.10,23.781213,sunny,0
420,422,2,9.0,0,1.670,50.0,3.0,180.0,483.0,10.00,17.928215,light,0
421,423,1,1.0,1,1.716,68.0,3.0,66.0,300.0,1.26,23.092680,super 666666,0

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedKFold
import numpy as np

X = df[['star_sign', 'phone_os', 'height', 'weight', 'sleepiness', 'iq', 'fb_friends', 'yt', 'bmi', 'emotion']]
y = df['gender'] - 1  

cv = StratifiedKFold(n_splits=5)

preprocessing_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')), 
    ('scaler', StandardScaler()),  
    ('feature_selection', SelectKBest(f_classif, k='all')), 
])

scores = []

for train_index, test_index in cv.split(X, y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    X_train_transformed = preprocessing_pipeline.fit_transform(X_train, y_train)
    X_test_transformed = preprocessing_pipeline.transform(X_test)
    
    feature_weights = [1] * (X_train_transformed.shape[1] - 1) + [1]  # Â∞ÜemotionÁâπÂæÅÁöÑÊùÉÈáçËÆæÁΩÆ‰∏∫30ÂÄç
    
    catboost = CatBoostClassifier(verbose=0, auto_class_weights='Balanced', feature_weights=feature_weights)
    
    catboost.fit(X_train_transformed, y_train)
    
    y_pred = catboost.predict(X_test_transformed)
    accuracy = accuracy_score(y_test, y_pred)
    scores.append(accuracy)

print('ÊØèÊ¨°‰∫§ÂèâÈ™åËØÅÁöÑÂáÜÁ°ÆÁéá:', scores)
print('Âπ≥ÂùáÂáÜÁ°ÆÁéá:', np.mean(scores))

ÊØèÊ¨°‰∫§ÂèâÈ™åËØÅÁöÑÂáÜÁ°ÆÁéá: [0.8235294117647058, 0.9058823529411765, 0.9404761904761905, 0.7976190476190477, 0.9285714285714286]
Âπ≥ÂùáÂáÜÁ°ÆÁéá: 0.8792156862745099

In [9]:
knn_test = pd.read_csv(r'preprocess_data/test_KNN_without_outlierBNI.csv')
knn_test['self_intro'] = knn_test['self_intro'].str.lower()
knn_test['emotion'] = np.vectorize(emotion_label)(knn_test['self_intro'])

X_knn_test = knn_test[['star_sign', 'phone_os', 'height', 'weight', 'sleepiness', 'iq', 'fb_friends', 'yt', 'bmi', 'emotion']]

X_knn_test_transformed = preprocessing_pipeline.transform(X_knn_test)

y_knn_pred = catboost.predict(X_knn_test_transformed)

output = knn_test[['id']].copy()
output['gender'] = y_knn_pred + 1 

output

      id  gender
0      1       1
1      2       1
2      3       2
3      4       1
4      5       2
..   ...     ...
390  391       2
391  392       1
392  393       2
393  394       1
394  395       1

[395 rows x 2 columns]

In [210]:
export_csv(output,'CatBoost_Sentiment_Dictionary')

In [28]:
test_data_copy = test_data.copy()
output = pd.read_csv(r'predict_data/CatBoost_Sentiment_Dictionary.csv')
test_data_copy.loc[:, 'gender'] = output['gender']

cleaned_test_data = test_data_copy.dropna(subset=['self_intro'])
cleaned_test_data.loc[:, 'self_intro'] = cleaned_test_data['self_intro'].str.lower()

info_data = cleaned_test_data[cleaned_test_data['self_intro'].str.contains('good')]

info_data

,id,gender,star_sign,phone_os,height,weight,sleepiness,iq,fb_friends,yt,self_intro
0,1,1,Â§©Ë†çÂ∫ß,Apple,NaN,100.0,1.0,87.0,87.0,87.0,good
26,27,1,ÁçÖÂ≠êÂ∫ß,Apple,173.0,70.0,5.0,126.0,250.0,0.1,i am a good man.
36,37,1,Â∞ÑÊâãÂ∫ß,Apple,176.0,90.0,3.0,120.0,705.0,11.0,eating is my life for good.
43,44,1,Êë©ÁæØÂ∫ß,Apple,171.0,60.0,2.0,125.0,749.0,2.6,good man
60,61,1,Â∞ÑÊâãÂ∫ß,Apple,178.0,45.0,4.0,200.0,500.0,1.0,good
68,69,1,ËôïÂ•≥Â∫ß,Apple,172.0,58.0,4.0,112.0,343.0,0.5,i‚Äôm good.
78,79,1,ÈáëÁâõÂ∫ß,NaN,NaN,63.0,4.0,NaN,500.0,NaN,i good
82,83,1,ËôïÂ•≥Â∫ß,Android,168.0,75.0,5.0,160.0,500.0,50.0,a good man.
116,117,1,ÈõôÈ≠öÂ∫ß,Android,180.0,80.0,5.0,110.0,139.0,0.5,i am good people
131,132,1,ÈáëÁâõÂ∫ß,Apple,173.0,62.0,5.0,123.0,600.0,35.2,i good
136,137,1,Â∑®ËüπÂ∫ß,Apple,169.0,67.0,5.0,199.0,500.0,100.0,"so smart, so handsome, so good"
146,147,1,Ê∞¥Áì∂Â∫ß,Apple,161.0,68.0,3.0,50.0,200.0,0.0,i'm a good person
153,154,2,Â∑®ËüπÂ∫ß,Apple,152.0,42.0,1.0,200.0,500.0,20.0,good
156,157,1,Â§©Áß§Â∫ß,Apple,180.0,77.0,1.0,180.0,1.0,10.0,good
167,168,1,NaN,Apple,178.0,NaN,NaN,NaN,129.0,140.0,good!
180,181,2,ÈõôÈ≠öÂ∫ß,Apple,163.0,60.0,4.0,180.0,385.0,100.0,i am good.
214,215,1,Â§©Ë†çÂ∫ß,Android,177.0,68.0,2.0,110.0,600.0,0.6,i'm so good.
253,254,1,ËôïÂ•≥Â∫ß,Apple,171.0,73.0,4.0,110.0,120.0,2.0,good person
309,310,1,ÈõôÈ≠öÂ∫ß,Apple,184.0,86.0,5.0,130.0,500.0,4.0,"like to make friends, wish everybody have a go..."
314,315,1,Â§©Ë†çÂ∫ß,Apple,185.0,82.0,3.0,95.0,500.0,100.0,i will be a good papa
323,324,1,NaN,Android,170.0,NaN,5.0,110.0,250.0,3.5,not really good at eng
324,325,1,NaN,NaN,NaN,52.0,NaN,90.0,800.0,NaN,good person
346,347,1,ÈõôÂ≠êÂ∫ß,Android,180.0,90.0,2.0,180.0,1000.0,6.0,so far so good
350,351,1,Êë©ÁæØÂ∫ß,Apple,163.0,100.0,3.0,55.0,3.0,5.0,good
374,375,1,Áâ°ÁæäÂ∫ß,Apple,179.0,72.0,3.0,130.0,78.0,119.0,i am a good person.

In [27]:
#ids_to_filter = [55, 78, 100, 271]
ids_to_filter = [27]
info_data = cleaned_test_data[cleaned_test_data['id'].isin(ids_to_filter)]
info_data

,id,gender,star_sign,phone_os,height,weight,sleepiness,iq,fb_friends,yt,self_intro
26,27,1,ÁçÖÂ≠êÂ∫ß,Apple,173.0,70.0,5.0,126.0,250.0,0.1,i am a good man.

In [123]:
#CatBoost_Sentiment_Dictionary_with‰∫∫Â∑•Ê®ôË®ò
#55 1 to 2
#78 1 to 2
#100 1 to 2
#271 1 to 2

In [25]:
import pandas as pd

high = pd.read_csv(r'predict_data/CatBoost_Sentiment_Dictionary_with‰∫∫Â∑•Ê®ôË®ò.csv')
low = pd.read_csv(r'predict_data/CatBoost_Sentiment_Dictionary_2024-04-02 01ÊôÇ53ÂàÜ52Áßí.csv')

merged = pd.merge(high, low, on='id', suffixes=('_high', '_low'))

different_gender = merged[merged['gender_high'] != merged['gender_low']]

print(different_gender)

      id  gender_high  gender_low
55    56            2           1
77    78            2           1
99   100            2           1
270  271            2           1

In [59]:
##ÊúâÂïèÈ°åË≥áÊñô
# 394 (I'm not beautiful, but smart)
# 16 (A young girl)
# 78 (I am a girl)
# 13 (Adorable)
# 55 (I'm a "Typical Lady".)
# 56 (I am so cuuuuuuute!)
# 100 (im cute)
# 189 (Ê≤íË≥áÊñô)
# 271 (>.0)

In [25]:
data_with_chinese = test_data[test_data['self_intro'].str.contains(r'[\u4e00-\u9fff]+', na=False)]
data_with_chinese

,id,gender,star_sign,phone_os,height,weight,sleepiness,iq,fb_friends,yt,self_intro
102,103,0,Â∑®ËüπÂ∫ß,Apple,172.0,90.0,4.0,120.0,100.0,0.3,Ë™çÁúüÁöÑÁî∑‰∫∫
103,104,0,ÈáëÁâõÂ∫ß,Android,173.0,84.0,5.0,150.0,250.0,10.0,ÈñãÊúóÊ®ÇËßÄ
244,245,0,Â∑®ËüπÂ∫ß,Apple,178.0,73.0,4.0,145.0,135.0,200.0,Êá∂
270,271,0,Â§©Áß§Â∫ß,Android,163.0,1.0,2.0,111.0,190.0,0.0,>.0ÂïæÂí™
386,387,0,Êë©ÁæØÂ∫ß,Apple,153.0,60.0,2.0,150.0,700.0,2.0,ÂèØÊÑõ