In [2]:
import pandas as pd
# from google.colab import drive
# drive.mount('/content/drive', force_remount=True)
# corpus_root = 'drive/My Drive/Colab Notebooks/data science and machine learning/Boy or Girl/'
# raw_data = pd.read_csv(corpus_root+'boy or girl 2024 train_missingValue.csv')

raw_data = pd.read_csv("boy or girl 2024 train_missingValue.csv")
raw_data

,id,gender,star_sign,phone_os,height,weight,sleepiness,iq,fb_friends,yt,self_intro
0,1,2,處女座,Apple,154.0,43.0,2.0,180.0,583.0,0,Beautiful
1,2,2,處女座,NaN,156.0,47.0,2.0,130.0,400.0,3.5,Enjoying being who I'm notsss
2,3,1,射手座,Android,170.0,61.0,3.0,90.0,540.0,5,Practice Makes perfect
3,4,1,射手座,Apple,170.0,62.0,4.0,100.0,173.0,5,Straightforward
4,5,2,射手座,Android,158.0,NaN,3.0,NaN,NaN,1.2,Humorous
...,...,...,...,...,...,...,...,...,...,...,...
418,419,1,處女座,Android,166.0,66.0,4.0,90.0,1000.0,1,I hope i am a super hero.
419,420,1,牡羊座,Android,176.0,65.0,4.0,87.0,1300.0,2,God damn dope
420,421,1,天秤座,Apple,174.0,72.0,NaN,NaN,NaN,NaN,Sunny
421,422,2,天蠍座,Apple,167.0,50.0,3.0,180.0,483.0,10,Light
422,423,1,雙魚座,Android,NaN,68.0,3.0,66.0,300.0,NaN,super 666666

In [3]:
# test_data = pd.read_csv(corpus_root+'boy or girl 2024 test no ans_missingValue.csv')
test_data = pd.read_csv("boy or girl 2024 test no ans_missingValue.csv")
test_data

,id,gender,star_sign,phone_os,height,weight,sleepiness,iq,fb_friends,yt,self_intro
0,1,0,天蠍座,Apple,NaN,100.0,1.0,87.000,87.0,87.0,GOod
1,2,0,金牛座,Apple,175.0,80.0,3.0,130.000,2000.0,30.0,Easygoing
2,3,0,雙子座,Apple,155.0,45.0,3.0,150.000,400.0,9.0,I LOVE INTEL
3,4,0,處女座,Apple,173.0,85.0,4.0,100.000,2000.0,15.0,"I'm a hard-work man, just do my best to finish..."
4,5,0,射手座,Android,164.0,57.0,4.0,130.000,505.0,2.0,I'm smart
...,...,...,...,...,...,...,...,...,...,...,...
390,391,0,處女座,Android,160.0,48.0,3.0,75.000,98.0,2.0,Starting by Starting
391,392,0,NaN,Apple,170.0,NaN,NaN,105.000,510.0,NaN,A little bit smart
392,393,0,金牛座,Apple,160.0,45.0,4.0,100.000,600.0,2000.0,Hi
393,394,0,巨蟹座,NaN,180.0,NaN,NaN,199.999,NaN,60.0,"I'm not beautiful, but smart 😀"
394,395,0,射手座,Apple,175.0,69.0,5.0,135.000,200.0,1400.0,Like the shadow

### 前處理

In [15]:
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

preprocess_data = raw_data.copy()
## 刪除手機極端值
preprocess_data = preprocess_data[preprocess_data['phone_os'] != 'JohnCena']

preprocess_data['star_sign'] = preprocess_data['star_sign'].astype('category')
preprocess_data['phone_os'] = preprocess_data['phone_os'].astype('category')
preprocess_data = pd.get_dummies(preprocess_data, columns=['star_sign', 'phone_os'])
preprocess_data.replace({True: 1, False: 0}, inplace=True)
## 處理缺失值
# height 170.00
# weight 63.00
# sleepiness 3.00
# iq 120.00
# fb_friends 400.00
# yt 2.00
preprocess_data['height'] = preprocess_data['height'].fillna(preprocess_data['height'].median())
preprocess_data['weight'] = preprocess_data['weight'].fillna(preprocess_data['weight'].median())
preprocess_data['sleepiness'] = preprocess_data['sleepiness'].fillna(preprocess_data['sleepiness'].median())
preprocess_data['iq'] = preprocess_data['iq'].fillna(preprocess_data['iq'].median())
preprocess_data['fb_friends'] = preprocess_data['fb_friends'].fillna(preprocess_data['fb_friends'].median())
preprocess_data['yt'] = pd.to_numeric(preprocess_data['yt'], errors='coerce')
preprocess_data['yt'] = preprocess_data['yt'].fillna(preprocess_data['yt'].median())

## 刪除身高體重極端值
preprocess_data = preprocess_data[preprocess_data['height'] <= 200.0]
preprocess_data = preprocess_data[preprocess_data['height'] >= 140.0]
preprocess_data = preprocess_data[preprocess_data['weight'] < 100.0]
preprocess_data = preprocess_data[preprocess_data['weight'] > 40.0]

## 標準化
scaler = StandardScaler()
preprocess_data[['height', 'weight']] = scaler.fit_transform(preprocess_data[['height', 'weight']])

preprocess_data

C:\Users\User\AppData\Local\Temp\ipykernel_22600\3259730144.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  preprocess_data.replace({True: 1, False: 0}, inplace=True)

,id,gender,height,weight,sleepiness,iq,fb_friends,yt,self_intro,star_sign_天秤座,...,star_sign_摩羯座,star_sign_水瓶座,star_sign_牡羊座,star_sign_獅子座,star_sign_處女座,star_sign_金牛座,star_sign_雙子座,star_sign_雙魚座,phone_os_Android,phone_os_Apple
0,1,2,-2.291550,-2.060322,2.0,180.0,583.0,0.0,Beautiful,0,...,0,0,0,0,1,0,0,0,0,1
1,2,2,-2.010715,-1.667284,2.0,130.0,400.0,3.5,Enjoying being who I'm notsss,0,...,0,0,0,0,1,0,0,0,0,0
2,3,1,-0.044873,-0.291652,3.0,90.0,540.0,5.0,Practice Makes perfect,0,...,0,0,0,0,0,0,0,0,1,0
3,4,1,-0.044873,-0.193393,4.0,100.0,173.0,5.0,Straightforward,0,...,0,0,0,0,0,0,0,0,0,1
4,5,2,-1.729881,0.052256,3.0,120.0,400.0,1.2,Humorous,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418,419,1,-0.606543,0.199645,4.0,90.0,1000.0,1.0,I hope i am a super hero.,0,...,0,0,0,0,1,0,0,0,1,0
419,420,1,0.797630,0.101385,4.0,87.0,1300.0,2.0,God damn dope,0,...,0,0,1,0,0,0,0,0,1,0
420,421,1,0.516796,0.789201,3.0,120.0,400.0,2.0,Sunny,1,...,0,0,0,0,0,0,0,0,0,1
421,422,2,-0.466125,-1.372506,3.0,180.0,483.0,10.0,Light,0,...,0,0,0,0,0,0,0,0,0,1
422,423,1,0.095544,0.396164,3.0,66.0,300.0,2.0,super 666666,0,...,0,0,0,0,0,0,0,1,1,0

### 架設模型

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Assuming preprocess_data is your preprocessed DataFrame
X = preprocess_data.drop(['gender', 'id', 'self_intro'], axis=1)
y = preprocess_data['gender']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=6)

# Initialize the decision tree classifier
dt_classifier = DecisionTreeClassifier(random_state=42)

# Train the classifier
dt_classifier.fit(X_train, y_train)

# Make predictions
y_pred = dt_classifier.predict(X_test)

# Evaluate the classifier
accuracy = accuracy_score(y_test, y_pred)
print(f'Decision Tree Classifier Accuracy: {accuracy}')

Decision Tree Classifier Accuracy: 0.8625

In [7]:
X_test['gender'] = y_test
X_test['pred'] = y_pred
X_test

,height,weight,sleepiness,iq,fb_friends,yt,star_sign_天秤座,star_sign_天蠍座,star_sign_射手座,star_sign_巨蟹座,...,star_sign_牡羊座,star_sign_獅子座,star_sign_處女座,star_sign_金牛座,star_sign_雙子座,star_sign_雙魚座,phone_os_Android,phone_os_Apple,gender,pred
118,-0.044873,-1.470766,1.0,122.0,1029.0,9.0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,1
300,-0.044873,0.396164,5.0,120.0,1300.0,5.0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,1
247,0.797630,1.771796,1.0,180.0,1.0,100.0,0,0,0,0,...,0,0,0,0,0,1,1,0,1,1
58,0.095544,0.003126,3.0,120.0,400.0,0.2,0,0,0,0,...,0,0,0,0,1,0,0,0,2,1
75,-0.044873,-0.389912,4.0,120.0,650.0,5.0,0,0,0,0,...,0,0,1,0,0,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,0.797630,0.052256,3.0,100.0,400.0,2.0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,1
365,0.095544,0.052256,3.0,120.0,600.0,2.0,0,0,1,0,...,0,0,0,0,0,0,0,0,2,1
140,0.095544,0.887461,2.0,180.0,400.0,2.0,1,0,0,0,...,0,0,0,0,0,0,0,1,1,1
3,-0.044873,-0.193393,4.0,100.0,173.0,5.0,0,0,1,0,...,0,0,0,0,0,0,0,1,1,1
18,-0.044873,-0.193393,4.0,100.0,173.0,5.0,0,0,1,0,...,0,0,0,0,0,0,0,1,1,1

In [9]:
filtered_data = X_test[X_test['gender'] != X_test['pred']]
filtered_data

,height,weight,sleepiness,iq,fb_friends,yt,star_sign_天秤座,star_sign_天蠍座,star_sign_射手座,star_sign_巨蟹座,...,star_sign_牡羊座,star_sign_獅子座,star_sign_處女座,star_sign_金牛座,star_sign_雙子座,star_sign_雙魚座,phone_os_Android,phone_os_Apple,gender,pred
58,0.095544,0.003126,3.0,120.0,400.0,0.2,0,0,0,0,...,0,0,0,0,1,0,0,0,2,1
105,0.095544,-0.389912,2.0,135.0,400.0,2.0,0,0,0,0,...,0,0,0,0,0,0,0,1,2,1
205,-0.325708,-1.470766,1.0,120.0,2000.0,2.0,0,0,0,0,...,0,1,0,0,0,0,0,1,2,1
87,0.095544,-1.372506,3.0,100.0,50.0,3.0,0,0,0,0,...,0,0,0,0,0,0,1,0,2,1
357,0.095544,-0.881209,3.0,120.0,600.0,1.0,0,0,0,0,...,0,0,0,0,0,0,0,1,2,1
93,-1.168212,-1.372506,2.0,140.0,1234.0,0.5,0,0,0,0,...,1,0,0,0,0,0,1,0,1,2
22,-0.044873,-0.684690,4.0,100.0,1200.0,2.0,0,0,0,0,...,0,0,0,0,1,0,1,0,2,1
365,0.095544,0.052256,3.0,120.0,600.0,2.0,0,0,1,0,...,0,0,0,0,0,0,0,0,2,1

### 測試集
#全男生1為0.65989 約 261
#全女生2為0.34010 約 134

In [ ]:
test_data

,id,gender,star_sign,phone_os,height,weight,sleepiness,iq,fb_friends,yt,self_intro
0,1,0,天蠍座,Apple,NaN,100.0,1.0,87.000,87.0,87.0,GOod
1,2,0,金牛座,Apple,175.0,80.0,3.0,130.000,2000.0,30.0,Easygoing
2,3,0,雙子座,Apple,155.0,45.0,3.0,150.000,400.0,9.0,I LOVE INTEL
3,4,0,處女座,Apple,173.0,85.0,4.0,100.000,2000.0,15.0,"I'm a hard-work man, just do my best to finish..."
4,5,0,射手座,Android,164.0,57.0,4.0,130.000,505.0,2.0,I'm smart
...,...,...,...,...,...,...,...,...,...,...,...
390,391,0,處女座,Android,160.0,48.0,3.0,75.000,98.0,2.0,Starting by Starting
391,392,0,NaN,Apple,170.0,NaN,NaN,105.000,510.0,NaN,A little bit smart
392,393,0,金牛座,Apple,160.0,45.0,4.0,100.000,600.0,2000.0,Hi
393,394,0,巨蟹座,NaN,180.0,NaN,NaN,199.999,NaN,60.0,"I'm not beautiful, but smart 😀"
394,395,0,射手座,Apple,175.0,69.0,5.0,135.000,200.0,1400.0,Like the shadow

In [ ]:
df = test_data.copy()
df['gender'] = df['gender'].map({0: '男性', 2: '女性'})
gender_phone_os = df.groupby(['phone_os', 'gender']).size().unstack(fill_value=0)
gender_phone_os

gender          男性
phone_os
Android        147
Apple          239
Windows phone    1

In [ ]:
import pandas as pd

# 設置顯示浮點數的格式
pd.set_option('display.float_format', '{:.2f}'.format)

# 您的其他程式碼...
weight_extreme_data = test_data[test_data['height'] > 180.0]
weight_extreme_data['weight'] = weight_extreme_data['weight'].apply(lambda x: float(x))
weight_extreme_data['height'] = weight_extreme_data['height'].apply(lambda x: float(x))
weight_extreme_data

<ipython-input-90-2542aa696af3>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weight_extreme_data['weight'] = weight_extreme_data['weight'].apply(lambda x: float(x))
<ipython-input-90-2542aa696af3>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weight_extreme_data['height'] = weight_extreme_data['height'].apply(lambda x: float(x))

,id,gender,star_sign,phone_os,height,weight,sleepiness,iq,fb_friends,yt,self_intro
10,11,0,天秤座,Android,190.00,89.00,2.00,120.00,185.00,0.00,A man with arrogance.
12,13,0,牡羊座,Apple,185.00,60.00,5.00,180.00,0.00,60.00,Adorable
15,16,0,NaN,Android,188.00,20.00,NaN,88.00,NaN,NaN,A young girl
25,26,0,天蠍座,Android,181.00,65.00,3.00,87.00,400.00,1.00,Hahahahaha
34,35,0,雙魚座,Android,187.00,66.00,4.00,150.00,150.00,0.10,Tall
53,54,0,雙魚座,Android,187.00,87.00,4.00,87.00,9487.00,5.95,I'm a 87.
56,57,0,處女座,Android,188.77,87.59,5.00,50.87,9487.00,8.74,Let's party!
71,72,0,牡羊座,Apple,218.00,50.00,4.00,200.00,0.00,1000.00,Ez game Ez life
88,89,0,天秤座,Android,200000.00,450000.00,2.00,180.00,345000000.00,0.00,I am so cute
91,92,0,牡羊座,Android,183.00,75.00,2.00,87.00,500.00,22.80,"I'm fine thank you,and you?"
92,93,0,巨蟹座,Apple,1844670000000000065536.00,1844670000000000267582938546176.00,1.00,200.00,9999999999999999583119736832.00,8.40,Plz do not delete my data.
97,98,0,處女座,Android,185.00,65.00,3.00,180.00,835.00,1.50,I'm so handsome.
108,109,0,雙魚座,Android,193.00,80.00,3.00,80.00,2300.00,0.80,I’m fine.
110,111,0,水瓶座,Android,183.00,72.00,3.00,180.00,250.00,2.00,Perfect man
165,166,0,處女座,Android,182.00,68.00,3.00,120.00,400.00,4.00,I am a slient man.
168,169,0,雙魚座,Apple,181.00,55.00,1.00,120.00,215.00,465.00,I’m look like tall and thin.
183,184,0,天蠍座,Apple,182.00,74.00,2.00,80.00,100.00,4.00,Sleepy
190,191,0,牡羊座,Apple,182.00,68.00,1.00,168.00,1303.00,99.20,"Cogito, ergo sum"
218,219,0,摩羯座,Android,183.00,76.00,2.00,200.00,262.00,1.00,so smart
220,221,0,雙魚座,Apple,183.00,60.00,1.00,199.00,300.00,30.00,HowDa U Sdd
222,223,0,雙魚座,Apple,380.00,380.00,5.00,60.00,0.00,500.00,random
223,224,0,NaN,Android,183.00,70.00,5.00,NaN,NaN,6666.00,Boiiiiiii
226,227,0,雙子座,Android,183.00,76.00,4.00,120.00,350.00,4.00,Wow
231,232,0,天蠍座,Apple,12345.00,400.00,3.00,90.00,700.00,52.00,Person
236,237,0,獅子座,Apple,190.00,92.00,4.00,200.00,837.00,144.00,"Never gonna give you up, never gonna let you d..."
238,239,0,雙魚座,Apple,183.00,60.00,1.00,199.00,300.00,30.00,HowDa U Sdd
239,240,0,獅子座,Apple,190.00,92.00,4.00,200.00,837.00,144.00,"Never gonna give you up, never gonna let you d..."
240,241,0,雙魚座,Apple,183.00,60.00,1.00,199.00,300.00,30.00,HowDa U Sdd
241,242,0,獅子座,Apple,190.00,92.00,4.00,200.00,837.00,144.00,"Never gonna give you up, never gonna let you d..."
242,243,0,獅子座,Apple,190.00,92.00,4.00,200.00,837.00,144.00,"Never gonna give you up, never gonna let you d..."
247,248,0,水瓶座,Android,182.00,100.00,2.00,180.00,500.00,32.00,I'm the best.
268,269,0,雙子座,Apple,183.00,94.00,4.00,120.00,881.00,12.10,A kind and optimistic person.
276,277,0,天蠍座,Apple,188.00,80.00,3.00,110.00,500.00,100.00,Keep breaking out of the comfort zone.
277,278,0,天秤座,Apple,185.00,97.00,3.00,100.00,400.00,1.00,Just do it.
309,310,0,雙魚座,Apple,184.00,86.00,5.00,130.00,500.00,4.00,"like to make friends, wish everybody have a go..."
314,315,0,天蠍座,Apple,185.00,82.00,3.00,95.00,500.00,100.00,I will be a Good papa
328,329,0,射手座,Android,185.00,98.00,1.00,95.00,70.00,50.00,"Student from Germany, originally Russian"
332,333,0,天蠍座,Apple,185.00,85.00,5.00,100.00,575.00,125.00,I am tall
355,356,0,處女座,Apple,191.00,77.00,1.00,83.00,410.00,31.00,"I do whatever i want. I am whatever i am, only..."
365,366,0,雙魚座,Apple,184.00,86.00,4.00,130.00,666.00,4.00,Confidence
366,367,0,牡羊座,Apple,181.00,80.00,1.00,200.00,1000.00,30.00,Smartttie
370,371,0,天蠍座,Apple,181.00,75.00,3.00,199.00,241.00,1000.00,"I want password card, plz"
373,374,0,天秤座,Apple,185.00,80.00,2.00,100.00,606.00,1330.00,Wang so rong

In [ ]:
output = test_data[['id', 'gender']]
output.loc[:, 'gender'] = 2
output

<ipython-input-17-d693d7da1d6f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  output.loc[:, 'gender'] = 2

      id  gender
0      1       2
1      2       2
2      3       2
3      4       2
4      5       2
..   ...     ...
390  391       2
391  392       2
392  393       2
393  394       2
394  395       2

[395 rows x 2 columns]

In [ ]:
import datetime
import pytz
def export_csv(df):
  now = datetime.datetime.now().astimezone(pytz.timezone('Asia/Taipei'))
  formatted_time = now.strftime('%Y-%m-%d %H時%M分%S秒')
  df.to_csv(corpus_root + formatted_time + "predict.csv", index=False,encoding="utf_8_sig")